definitions:
  v1.StartStreamReq:
    description: 启动设备流请求参数
    properties:
      deviceId:
        example: 127.0.0.1:16480
        type: string
    type: object
  v1.StartStreamRes:
    description: 启动设备流响应参数
    properties:
      port:
        example: 8886
        type: integer
      url:
        example: ws://localhost:8886
        type: string
    type: object
  v1.StopStreamReq:
    description: 停止设备流请求参数
    properties:
      deviceId:
        example: 127.0.0.1:16480
        type: string
    type: object
  v1.StopStreamRes:
    description: 停止设备流响应参数
    type: object
info:
  contact: {}
paths:
  /scrcpy/stream/start:
    post:
      consumes:
      - application/json
      description: 为指定设备启动scrcpy流服务，返回WebSocket连接地址
      parameters:
      - description: 请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.StartStreamReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.StartStreamRes'
      summary: 启动设备流服务
      tags:
      - 串流管理
  /scrcpy/stream/stop:
    post:
      consumes:
      - application/json
      description: 停止指定设备的scrcpy流服务
      parameters:
      - description: 请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.StopStreamReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.StopStreamRes'
      summary: 停止设备流服务
      tags:
      - 串流管理
swagger: "2.0"
