// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalFileDao is an internal type for wrapping the internal DAO implementation.
type internalFileDao = *internal.FileDao

// fileDao is the data access object for the table file.
// You can define custom methods on it to extend its functionality as needed.
type fileDao struct {
	internalFileDao
}

var (
	// File is a globally accessible object for table file operations.
	File = fileDao{
		internal.NewFileDao(),
	}
)

// Add your custom methods and functionality below.
